// Generated by gencpp from file lab1/MapperMessage.msg
// DO NOT EDIT!


#ifndef LAB1_MESSAGE_MAPPERMESSAGE_H
#define LAB1_MESSAGE_MAPPERMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab1
{
template <class ContainerAllocator>
struct MapperMessage_
{
  typedef MapperMessage_<ContainerAllocator> Type;

  MapperMessage_()
    : x(0)
    , y(0)
    , theta(0)
    , d(0)  {
    }
  MapperMessage_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , theta(0)
    , d(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _theta_type;
  _theta_type theta;

   typedef int32_t _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::lab1::MapperMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab1::MapperMessage_<ContainerAllocator> const> ConstPtr;

}; // struct MapperMessage_

typedef ::lab1::MapperMessage_<std::allocator<void> > MapperMessage;

typedef boost::shared_ptr< ::lab1::MapperMessage > MapperMessagePtr;
typedef boost::shared_ptr< ::lab1::MapperMessage const> MapperMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab1::MapperMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab1::MapperMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lab1': ['/home/robot5/tyler_scratch/src/lab1/msg', '/home/robot5/tyler_scratch/src/lab1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab1::MapperMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab1::MapperMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab1::MapperMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab1::MapperMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab1::MapperMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab1::MapperMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab1::MapperMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20b51b83ff10e216b97e63c312c297ed";
  }

  static const char* value(const ::lab1::MapperMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20b51b83ff10e216ULL;
  static const uint64_t static_value2 = 0xb97e63c312c297edULL;
};

template<class ContainerAllocator>
struct DataType< ::lab1::MapperMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab1/MapperMessage";
  }

  static const char* value(const ::lab1::MapperMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab1::MapperMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 theta\n\
int32 d\n\
";
  }

  static const char* value(const ::lab1::MapperMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab1::MapperMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapperMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab1::MapperMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab1::MapperMessage_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.theta);
    s << indent << "d: ";
    Printer<int32_t>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB1_MESSAGE_MAPPERMESSAGE_H
